require("flash.plugins-setup")
require("flash.core.options")
require("flash.core.keymaps")
require("flash.core.colorscheme")
require("flash.plugins.comment")
require("flash.plugins.nvim-tree")
require("flash.plugins.lualine")
require("flash.plugins.telescope")
require("flash.plugins.nvim-cmp")
require("flash.plugins.lsp.mason")
require("flash.plugins.lsp.lspsaga")
require("flash.plugins.lsp.lspconfig")
require("flash.plugins.lsp.null-ls")
require("flash.plugins.autopairs")
require("flash.plugins.treesitter")
require("flash.plugins.gitsigns")
require("flash.plugins.toggleterm")
require("flash.plugins.ufo")

vim.cmd([[silent! autocmd! filetypedetect BufRead,BufNewFile *.tf]])
vim.cmd([[autocmd BufRead,BufNewFile *.hcl set filetype=hcl]])
vim.cmd([[autocmd BufRead,BufNewFile .terraformrc,terraform.rc set filetype=hcl]])
vim.cmd([[autocmd BufRead,BufNewFile *.tf,*.tfvars set filetype=terraform]])
vim.cmd([[autocmd BufRead,BufNewFile *.tfstate,*.tfstate.backup set filetype=json]])
